# Generated by Django 4.0.5 on 2022-06-07 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='post_image'),
            preserve_default=False,
        ),
    ]
